### ISSUE TITLE
returning 'undefined' instead of 'World' when using curl

### ISSUE THREAD

**Issue by ghost** [bucharest-gold/nodejs-configmap-redhat#4]
When deployed to OpenShift, this booster performs as follows:

```bash
$ curl http://ROUTE_NAME/api/greeting
{"content":"Hello, undefined from a ConfigMap !"}
```

it should be:

```bash
$ curl http://ROUTE_NAME/api/greeting
{"content":"Hello, World from a ConfigMap !"}
```

Steps to reproduce:
1. Follow instructions in docs to deploy booster, e.g. https://appdev.openshift.io/docs/nodejs-runtime.html#deploying-the-configmap-booster-using-the-oc-cli-client_configmap-oso
2. Run `curl http://ROUTE_NAME/api/greeting`

**Comment by ghost** [comment]
FYI @Ladicek

**Comment by lholmquist** [comment]
@rhoads-zach i see the issue,  should be an easy fix

**Comment by Ladicek** [comment]
Thanks @rhoads-zach @lholmquist!
