### ISSUE TITLE
configmap example doesn't work on OpenShift

### ISSUE THREAD

**Issue by hrishin** [bucharest-gold/nodejs-configmap-redhat#55]
**Problem:**

API keep saying "Unable to read the configuration" though `configmap` does exists. The application fails to query the configmap because of permission issue. However, while applying the given `role.resources` also fails because of the permission issue.

**Solution:**

It would be nice to mount the configmap map as a volume/ENV VAR and read the configuration (preferred practice) if it fails to query the configmap.

@lholmquist

**Comment by lholmquist** [comment]
which openshift is this failing on?  OKD, openshift.io, OCP?

**Comment by hrishin** [comment]
@lholmquist OSO (Openshift Online) for OSIO (openshift.io) use case.

**Comment by lholmquist** [comment]
how are you deploying it?  using the template? using nodeshift?

**Comment by hrishin** [comment]
@lholmquist using the template https://github.com/bucharest-gold/nodejs-configmap-redhat/blob/master/.openshiftio/resource.roles.yaml. We have also tried using https://github.com/bucharest-gold/nodejs-configmap-redhat/blob/master/Jenkinsfile#L4.

**Comment by lholmquist** [comment]
@hrishin i guess my question was how is the application deployed?  Have you tried any of the other runtimes? for example, https://github.com/openshiftio-vertx-boosters/vertx-configmap-booster-redhat or https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-configmap

I'm wondering if the issue is just on the node booster

**Comment by hrishin** [comment]
@lholmquist Yes, I've tried other Java runtimes. It deploys the application using fabric8 maven plugin (FMP) and creates an configmap in Jenkins workflow. However, the application [DC](https://github.com/openshiftio-vertx-boosters/vertx-configmap-booster-redhat/blob/master/src/main/fabric8/deployment.yaml) has the `volume` definition pointing to configmap, I guess Java application reads the message template from configuration.

**Comment by lholmquist** [comment]
@hrishin i'm in the process of adding the configmap as a volume and accessing that way, but could you do me a favor and try this branch, https://github.com/lholmquist/nodejs-configmap-redhat/tree/fun-with-console-log-debugging

i've added some console logs to see where/what the error is

**Comment by lholmquist** [comment]
@hrishin config map is now a volume mount, here is the PR that got merged #58 

I've put in a PR to the launcher booster catalog to update with these latest versions.  let me know how it goes

**Comment by hrishin** [comment]
Lovely @lholmquist 

Thank you!
